### ISSUE TITLE
 Multiple CORS header ‘Access-Control-Allow-Origin’ not allowed if service having a CORS middleware

### ISSUE THREAD

**Issue by acabarbaye** [devopsfaith/krakend-cors#18]
I have a gateway in front of services and I set the gateway CORS policy as described in the documentation.
```yaml
extra_config:
  github_com/devopsfaith/krakend-cors:
    allow_origins:
    - "......"
    allow_methods:
    - GET
    - POST
    - DELETE
    - OPTIONS
    - HEAD
    allow_headers:
    - Accept
    - Authorization
    - Content-Type
    - Accept-Version
    expose_headers:
    - Link
    allow_credentials: false
    max_age: 5m
```
Nonetheless, one of the subservices the gateway is in front of also has a CORS middleware and hence, sets the different headers. I would expect the gateway to take precedence and overwrite the headers with its own configuration instead of adding more headers, leading to the following issue:  `Multiple CORS header ‘Access-Control-Allow-Origin’ not allowed`

![image](https://user-images.githubusercontent.com/29707928/137885853-aef2701f-823e-4da3-8673-577fec320716.png)
